### ISSUE TITLE
OpenGL 2.1

### ISSUE THREAD

**Issue by Zero87879** [McKay42/McOsu#107]
Every time i open up McOsu,i get a OpenGL 2.1 error.
Am i forced to use OpenGL 2.1?
Please help.

I also have OpenGL ES 2.0,just saying.

**Comment by McKay42** [comment]
This is not really a github issue. Also, you are using an old version, since the actual OpenGL requirement is version 3.0 or above. If your GPU doesn't support OpenGL 3.0 or higher then it will crash after the warning message.
Supporting older OpenGL versions is not a goal at this time.
