### ISSUE TITLE
CS Override is not compatible with Minimize

### ISSUE THREAD

**Issue by quat1024** [McKay42/McOsu#112]
What I expected:

Overriding the map to CS6 and using Minimize would cause the circles to start at CS6 and end up half as big.

What happened:

The map stayed CS6 forever and the Minimize effect was ignored.

**Comment by yuxuanchiadm** [comment]
I can reproduce. Trying to figure it out and fix it.

**Comment by yuxuanchiadm** [comment]
So this issue is caused by the order of CS calculation. Currently we apply Minimize multiplier first then override CS. So we don't see any effect of Minimize mode. The simple fix is reverse it. I'll submit PR later.

**Comment by McKay42** [comment]
This has been fixed quite some time ago (on the Steam version of course)
