### ISSUE TITLE
slider approach circles appear before they should

### ISSUE THREAD

**Issue by TsundereDwarf** [McKay42/McOsu#12]
example: (also features #11)

https://www.youtube.com/watch?v=QAyrd1JYAdg&feature=youtu.be

**Comment by McKay42** [comment]
This is because on older maps there was no AR stored, and the OD should be used for both the OD and the AR.
> https://github.com/McKay42/McOsu/issues/14

**Comment by McKay42** [comment]
(Currently, the default AR is 5 if nothing could be loaded from a beatmap)
