### ISSUE TITLE
Linux 27 patch release?

### ISSUE THREAD

**Issue by Zeredan** [McKay42/McOsu#123]
I know, I know. There are more Windows users than Linux, but can you make the new 27 patch available, or I don't know if it's possible but even the VR version?

**Comment by McKay42** [comment]
I'm working on it, you can already play the latest Linux testversion on Steam if you enter the beta access code "linuxtest123" and switch to the linuxtest beta.

**Comment by McKay42** [comment]
pls close issues when you open them and they are finished thx
(A stable Linux build is now on Steam, without needing any beta participation)
