### ISSUE TITLE
"CursorRotate: 0" not working

### ISSUE THREAD

**Issue by Macacito** [McKay42/McOsu#127]
.

**Comment by yuxuanchiadm** [comment]
Can not reproduce. What does "not working" mean?
Try check you are using what skin you want.

**Comment by McKay42** [comment]
Some people have had skins where the skin.ini text file was encoded in UCS-2 or other strange formats, can you check that for your skin with notepad++? You can also use notepad++ to convert the encoding to UTF-8 or ANSI, both of which will work. UCS-2 text files will _not_ work.

**Comment by yuxuanchiadm** [comment]
So if is this is caused by encoding problem. Should we warning about it when switching skin and we got unsupported char? Or do some character encoding prediction?

**Comment by McKay42** [comment]
a warning would probably be the best solution, closing this for now
