### ISSUE TITLE
Custom Hitsounds not working

### ISSUE THREAD

**Issue by sdsadasda** [McKay42/McOsu#135]
Im using totoris skin and any skin I choose does not have the custom hitsounds it has,only wwws new skin has custom hitsounds that I can see in mcosu.
I need help

**Comment by McKay42** [comment]
That's because of https://github.com/McKay42/McOsu/issues/21 , I'll fix it

**Comment by McKay42** [comment]
ok the skin should work now at least visually, although I don't understand what you mean with the hitsounds. Hitsound additions are not yet implemented, but the basic hitsounds from the Totori skin do work as expected (drum, normal, soft). (Nightcore hitsounds are also not yet implemented)
Which hitsounds do you mean exactly?
Which skin (Totori has multiple skins)?

**Comment by McKay42** [comment]
closed because of inactivity
