### ISSUE TITLE
Allow beatmap difficulty overrides to use relative offsets

### ISSUE THREAD

**Issue by JTF195** [McKay42/McOsu#140]
Beatmap difficulty mod sliders currently set a constant override value

It would be nice if there were an option to use a relative offset instead. (or a mix of the two)

So, for example, rather than overriding all beatmaps to AR9, you could increase them each by AR+1

This concept would work with multipliers as well (like HR/EZ, only with user-defined values)

I already added more or less the same feature to my rewrite of [MapSettingsCustomizer](https://github.com/JTF195/MapSettingsCustomizer) (sensing a pattern here?) so it shouldn't be too hard to add.

 I'll work on it.

**Comment by McKay42** [comment]
The OsuModSelector class here is still a bit of a shitshow (especially onOverrideSliderChange() and getOverrideSliderLabelText()), it needs some major cleanup and restructuring to make implementing stuff like this easier. You have been warned ^^

(This would go nicely together with https://github.com/McKay42/McOsu/issues/118)

**Comment by JTF195** [comment]
There are also enough experimental mods (and more on the way, I'm sure) that, rather than scrolling the list, it might warrant redesigning the main portion of the menu itself.

I'm not sure the 3x5 icon grid is even the right approach anymore.

**Comment by JTF195** [comment]
Bringing up MapSettingsCustomizer gave me another idea: add an option to change the sliders to floor+ceiling instead of a single value. difficulty values between the floor and ceiling will be left alone, but outliers will be adjusted.

And another option: filter beatmaps by difficulty settings with the above sliders instead of adjusting the outliers.

**Comment by McKay42** [comment]
Doesn't really seem that useful anymore since the AR/OD locks have been added.
