### ISSUE TITLE
Full alternate mod is too agressive

### ISSUE THREAD

**Issue by NikWillOrStuff** [McKay42/McOsu#154]
The mod currently defaults to only letting you start with the Left click key, or "remembers" what button you last pressed in situations where it would be more ideal to allow the user to start with either key. Here are the situations where I've run into this problem:
Picking a new song, restarting the current song, breaks, spinners, and missing several notes.

p.s. Mcosu is great, thanks for your work :D

**Comment by McKay42** [comment]
Was fixed in 30.12
