### ISSUE TITLE
Mania Speed?

### ISSUE THREAD

**Issue by BrinK229** [McKay42/McOsu#158]
Just starting today I went to play McOsu and I hit the right cursor key, I'm getting something about changing Mania speed. I'm left handed so I aim with my left and tap with right and use the cursor keys. There doesn't seem to be any bind in the options that let's me turn that off. Hope there's some kind of fix to help with that. 

Also, neat to see you're adding support for Mania. (If that is what you're doing.)

**Comment by SlowLogicBoy** [comment]
I think answer for mania is here #157

**Comment by McKay42** [comment]
Forgot to comment the piece of code for that, will be fixed shortly.
