### ISSUE TITLE
how do i build this

### ISSUE THREAD

**Issue by iptq** [McKay42/McOsu#161]
thank

**Comment by McKay42** [comment]
I'm sure you can figure it out by reading the readme.
It's definitely not as easy as writing a python script.
Note that the code in this repository is _only_ the game code, and doesn't include the McEngine code, which should be pretty obvious when you look at it.

**Comment by NickTheHuy** [comment]
is there a way to still build it if i have the mcengine code?

**Comment by McKay42** [comment]
> is there a way to still build it if i have the mcengine code?

I don't understand your question. Of course you can build it, the master branches of both engine and game repos are what the Steam build is created from.
