### ISSUE TITLE
VR hmd position auto reset in mid-game

### ISSUE THREAD

**Issue by RoyalShooter** [McKay42/McOsu#162]
I have a several time in mid-game, the game reset the HMD position, resulting in the play area position changed in the mid-game. Would you mine to turn off the auto reposition in the mid-game. (or maybe make a button for it) Thanks.

**Comment by McKay42** [comment]
That's what the layout lock button is for: https://imgur.com/a/uVOm0
Once activated, you can no longer move anything (except if you unlock it again by clicking the same lock button).
