### ISSUE TITLE
Beatmap not working

### ISSUE THREAD

**Issue by nermolov** [McKay42/McOsu#163]
Sorry for the extremely indescriptive issue:

https://osu.ppy.sh/b/1088933

McOsu works fine on my machine and other maps work perfectly, but after extracting this and placing the folder in the Songs folder, the song is not visible in the songs list. I tried comparing its contents with that of another working one and I couldn't deduce any reason for it to not work.

Running on Arch Linux.

**Comment by McKay42** [comment]
This beatmap contains exclusively osu!mania difficulties, while only the osu!standard gamemode is supported currently. Only beatmaps which can actually be played are shown in the songbrowser.
