### ISSUE TITLE
[Linux] Raw input not functional

### ISSUE THREAD

**Issue by cory2067** [McKay42/McOsu#170]
Linux Mint 18.3, trying to apply raw input to tablet.

As it currently stands, I don't have a way to change tablet sensitivity in McOsu, since raw input doesn't seem to be functional, and the sensitivity bar doesn't affect the tablet.

**Comment by McKay42** [comment]
https://askubuntu.com/questions/572267/how-to-change-pen-movement-speed-on-wacom-tablet

It should also work for non-Wacom tablets (try both xsetwacom and xinput as described).
Using the in-game sensitivity to change the tablet area is a very bad idea anyway, you should always use the software provided with your tablet.

(Tablets have nothing to do with raw input. Raw input is only relevant for mice.)

https://github.com/McKay42/McEngine/issues
