### ISSUE TITLE
High input latency

### ISSUE THREAD

**Issue by takase1121** [McKay42/McOsu#171]
The input latency become high after enabling the backgrounds. It rises from `~8ms` to `9-10 ms`. Even if I don't enable the backgrounds, the input latency was twice of my osu!(osu!: `~4ms`, McOsu: `~8ms` ). Please help.

**Comment by McKay42** [comment]
If you are on a laptop with multiple GPUs (e.g. a crappy integrated Intel one, and a faster dedicated Nvidia/AMD one), make sure the game is running on the faster GPU (google Nvidia Optimus, Switchable Graphics).

If you can really only reach 250 fps (4ms) even in osu, then your computer is too slow for timing-critical rhythm games. Sorry, but I'm not going to invest massive amounts of time into optimizing for such hardware.
