### ISSUE TITLE
Instant crash as of Radeon Adrenalin

### ISSUE THREAD

**Issue by ThatOneCheetah** [McKay42/McOsu#172]
Process stops working instantly after start; JIT debugger catches this:
```
Unhandled exception at 0x65C4D961 in McEngine.exe: 0xC0000005: Access violation reading location 0x00000000. occurred
```
with the following call stack:
```
00000000()
[Frames below may be incorrect and/or missing]
atioglxx.dll!562f43f4()
atioglxx.dll!562faf85()
atioglxx.dll!562f0391()
```

This started happening after I updated from Radeon Software Version `18.1.1` to `18.2.1`.  
*(clean install with DDU was performed)*

**Relevant specifications**
```
CPU: Intel i5-2500K (stock speed)
GPU: MSI Radeon RX 480 Gaming X 8G (stock speed, +50% power usage allowance)
OS : Windows 10 Home N (media feature pack installed)
```

**Comment by McKay42** [comment]
Thanks for the detailed report, but I don't think that I can fix this.
Seems like it's a problem on AMD's side, we will see if other people are affected.
