### ISSUE TITLE
Windows Mixed Reality

### ISSUE THREAD

**Issue by Drison64** [McKay42/McOsu#176]
Hello, i have an idea, that McOsu could be for Windows Mixed Reality too, i would play it on

**Comment by McKay42** [comment]
SteamVR provides support for WMR, all SteamVR games should work without the developer having to do anything. According to someone on the discord, it works just fine.

**Comment by RealistikDash** [comment]
They should then update this 
![image](https://user-images.githubusercontent.com/36131887/50739356-0e799280-11d7-11e9-9bb3-188608e58b8e.png)

**Comment by McKay42** [comment]
> 
> 
> They should then update this
> ![image](https://user-images.githubusercontent.com/36131887/50739356-0e799280-11d7-11e9-9bb3-188608e58b8e.png)

I don't own a WMR headset, therefore I can't "officially" support it since I can't test it (and therefore also can't provide workarounds/fixes if something needs tweaking).
