### ISSUE TITLE
McOsu freezes on launch.

### ISSUE THREAD

**Issue by xenosu** [McKay42/McOsu#177]
Exactly what the title says.
Eventually McOsu just doesn't respond and then stops working.

CPU: intel i7 7th gen
GPU: Nvidia GTX 1050
8gb ram

[debug](https://docs.google.com/document/d/17GmiDuRWE1KdLmS1BQOjnjwOVPW0szr2VKICjoPHAvA/edit?usp=sharing)

**Comment by McKay42** [comment]
Eventually? How often? Also, the log doesn't seem to be from a freeze, everything looks normal there.
Try to start the debug exe a few times and see if you can get it to freeze, then screenshot the log window.
Exotic audio devices/drivers can sometimes cause problems, what is yours?

**Comment by xenosu** [comment]
happens every time i've opened mcosu
i have nahimic but during these screenshots i've turned it off
i have a logitech G230 headset

![screenshot 1](https://user-images.githubusercontent.com/35980509/36402074-cc7ec0d2-15a9-11e8-89ae-4e367f441ddb.png)
![screenshot 2](https://user-images.githubusercontent.com/35980509/36402075-cc8ff92e-15a9-11e8-8a67-150b32e29de9.png)
![screenshot 3](https://user-images.githubusercontent.com/35980509/36402076-cc9c8162-15a9-11e8-98db-0fe3f7bf6844.png)
![screenshot 4](https://user-images.githubusercontent.com/35980509/36402171-78295924-15aa-11e8-805a-69b42a65a352.png)
![screenshot 5](https://user-images.githubusercontent.com/35980509/36402172-783787e2-15aa-11e8-9093-a25f53a49a6e.png)
![screenshot 6](https://user-images.githubusercontent.com/35980509/36402174-7bfe444c-15aa-11e8-973a-e5af3b518322.png)

**Comment by McKay42** [comment]
Please switch to the cutting-edge beta in the right-click properties of the game in your library, and try it again. (Steam > Library > right click on game > Properties > BETAS > select "cutting-edge - Experimental")
I'm testing something, it will probably still crash though.

The difficult part of debugging this is that the engine managed to survive a few frames like nothing was wrong, so my best guess is that something running on your computer is waiting periodically and injecting itself into the game process (maybe Nahimic/Audio related, who knows).

**Comment by xenosu** [comment]
you were right
![screenshot 7](https://user-images.githubusercontent.com/35980509/36463197-4d5c4e58-1696-11e8-9ab5-571803e12169.png)
i also found that mcosu still uses the cpu so i'll try again while i sleep to just wait on the screen
it probably will just crash again though
![screenshot 8](https://user-images.githubusercontent.com/35980509/36463198-4d6e13ae-1696-11e8-8a68-7ffa2b124d30.png)
![screenshot 9](https://user-images.githubusercontent.com/35980509/36463199-4d7b05aa-1696-11e8-863c-49f5689c5fda.png)

**Comment by McKay42** [comment]
If you have the time and are up for it, hit me up on Discord for a more interactive debugging session:
https://discord.gg/3UQnt7X

This way I can change the code and directly get feedback, should be a lot quicker.
One of the first things to try is giving you an empty engine executable, to see if it has anything to do with the game code. Then I can keep disabling/enabling parts of it until it starts crashing.

**Comment by xenosu** [comment]
fixed, reinstalled intel and nvidia drivers

**Comment by McKay42** [comment]
Interesting, so my guess was correct.

For documentation purposes: The graphics driver crashed/blocked/froze at the first occurring SwapBuffers() call, giving an unknown signal, and taking the game down with it.

The call stack looked like this (separate thread, this was **not** in the main game thread!):
```
vk_optimusGetInstanceProcAddr()
...
nvoglv32!DrvPresentBuffers()
...
```
Running on OpenGL, not Vulkan, even though at the top is a Vulkan function (internally from the driver, apparently). The main game thread was stuck waiting for SwapBuffers() to return.
