### ISSUE TITLE
VR View Fullscreen

### ISSUE THREAD

**Issue by NotToBlame** [McKay42/McOsu#178]
Really short one. Could be a missing feature, I could be dumb and missing it or could be a suggestion but is there a possibility of making the view from VR fullscreen and not showing left and right eye or using the positional camera

**Comment by McKay42** [comment]
Read through the options again.
Options > Virtual Reality > Miscellaneous > "Draw HMD to Window"
Options > Virtual Reality > Miscellaneous > "Draw Both Eyes to Window"
Options > Graphics > Layout > "Fullscreen"

If you disable "Draw HMD to Window", then you will just see the standard 2d playfield, albeit with the 2 VR cursors projected onto it. (Any VR view is only shown as long as this option is enabled)
