### ISSUE TITLE
McOsu gets confused when using CJK input.

### ISSUE THREAD

**Issue by Gyyyn** [McKay42/McOsu#182]
Tested with Microsoft IME and Google IME on japanese mode. McOsu starts having delay when ESC is inputted and straight up stops responding to key taps when playing.

**Comment by McKay42** [comment]
Please confirm if the fix is working:
In your Steam library, right click on the game > Properties > BETAS > select "cutting-edge".

**Comment by Gyyyn** [comment]
Comfirmed. Thank you very much!
