### ISSUE TITLE
Touchscreen not working

### ISSUE THREAD

**Issue by Inappreciation** [McKay42/McOsu#188]
When I try to use touchscreen on McOsu, it just glitches and either makes it miss, or get a 50. I've tried ignore sens & raw input, windows ink work around and os tabletpc support and nothing works. how do i fix this?

**Comment by McKay42** [comment]
> how do i fix this?

**Comment by McKay42** [comment]
> how do i fix this?

You don't, I have to fix it at the engine/framework level.
Since I don't own a touchscreen device running windows/linux/macos for testing, touchscreen is not officially supported yet.
