### ISSUE TITLE
Option: Disable Score System

### ISSUE THREAD

**Issue by Bleikind** [McKay42/McOsu#191]
I would like to disable the new score system (v29). I have nothing against it, but i dont like it.
In the option menu a little tick to enable to show it or to hide it would be nice!

**Comment by McKay42** [comment]
For the time being, you can disable the in-game scoreboard by either pressing TAB (Options > Input > Keyboard > "Toggle Scoreboard" binding), or by disabling it directly in Options > Gameplay > HUD > "Draw ScoreBoard".

**Comment by Bleikind** [comment]
Yea, already saw it. But could there be a function to enable or disable this later?

**Comment by McKay42** [comment]
Yes, I'll add a toggle.

**Comment by Bleikind** [comment]
Okay, thank you!

**Comment by McKay42** [comment]
Issues are kind of like a todo list, you usually keep them open until resolved/implemented

**Comment by Bleikind** [comment]
Oh im sorry, I did that reflexively ups

**Comment by McKay42** [comment]
I've decided to make it a ConVar only (`0` is disabled, `1` is enabled):
`osu_scores_enabled 0`

Simply add this command to your osu cfg (`/<Steam>/steamapps/common/McOsu/cfg/osu.cfg`).
