### ISSUE TITLE
Skipping Around in Song

### ISSUE THREAD

**Issue by kzendo** [McKay42/McOsu#204]
Just started McOsu. Haven't played in a hot minute. Every time I start a song the song skips around every where. The beat map starts at the beginning like usual, then it skips to the end, to the middle, back to 3/4 back to the beginning and hops all over the place. I uninstalled and reinstalled its just not working lol

**Comment by McKay42** [comment]
You have to tell me a lot more about your system.

1. Windows, Linux, macOS? Which version? Updates installed?
2. Audio driver version and hardware name?
3. Are you accidentally holding/touching your SHIFT key and scrubbing around the song while left mouse click is down?

Please record a video of the skipping.

**Comment by kzendo** [comment]
I didn't realize I was tapping shift lol i feel stupid. I just rebound the key. thanks :P
