### ISSUE TITLE
Profile support

### ISSUE THREAD

**Issue by sourcandy** [McKay42/McOsu#215]
Considering that McOsu received scores.db support, a nice addition would be to have the ability to make a custom profile with a list of all of our best plays. (either combined with the scores from scores.db, or separate) I'm sure a lot of people would be happy with this addition, since having something to compare our plays to (even if the pp system is flawed) provides a good feedback loop to keep playing. However, it's true that a lot of people play McOsu just to avoid the need to play for pp, and just enjoy the game, so it would of course be optional. Having it more liberal than the osu system would also be nice, with the ability to delete/hide plays that we don't want, or not submit them at all.
Thank you :)

**Comment by McKay42** [comment]
Yes, you're not the first to suggest this. All McOsu scores already store extra data containing pp, stars, number of slider breaks, unstable rate, etc. for some kind of local user statistics page in the future.
The only thing left to do is building a UI for it, which is the annoying time consuming part.
