### ISSUE TITLE
Sorting by pp

### ISSUE THREAD

**Issue by sourcandy** [McKay42/McOsu#220]
Sorting by pp gained for 100% FC (depending on how hard it is, would be nice to have 99%, 98% as well)
Why? Because pp is more accurate and useful than star rating in most cases. Example being a long, high OD 5.5* map is a decent bit harder than a tv size 6* and star rating doesn't reflect that.
Not sure if pp is stored anywhere or just calculated on the go, so this might not be worth the effort to implement but it sure would be nice to have.

**Comment by McKay42** [comment]
Added to https://github.com/McKay42/McOsu/issues/73
