### ISSUE TITLE
Copy score to clipboard

### ISSUE THREAD

**Issue by sourcandy** [McKay42/McOsu#224]
**Usage**
User would press a hotkey on the result screen (ctrl+c if that's currently unused), and McOsu would copy the important information to the clipboard. Would be nice to have separate 'simple' and 'verbose' outputs, with a hotkey corresponding to each (ctrl+shift+c for verbose perhaps).
'simple' would only have the title, difficulty, mods, pp and accuracy (or something along those lines), and 'verbose' would have pretty much everything that we can see on the results screen (simple+UR, 300/100/50/miss, difficulty+breakdown, date, etc)

**Why**
Would be useful for quickly sending scores to friends or stream (because it's much faster than taking a screenshot, especially through steam), and inputting them to outside programs (say, a score keeping program that calculates total pp)

**Comment by McKay42** [comment]
Too niche, especially now since we have local scores and profile pp.
