### ISSUE TITLE
Auto glitch

### ISSUE THREAD

**Issue by isiahah** [McKay42/McOsu#227]
So i was playing mcosu and then i wanted to test if i could get pp out of auto, i found it could.
the video link is 
https://www.youtube.com/watch?v=anEpvzeQq_M

**Comment by McKay42** [comment]
Yes, I know this is possible. This is not a glitch, you know fully well what you are doing.
This is an offline practice client.

**Comment by McKay42** [comment]
You can just right click and delete a score like this if it happens by accident.
