### ISSUE TITLE
Auto adjust hitresult fadeout duration for Speed Multiplier

### ISSUE THREAD

**Issue by McKay42** [McKay42/McOsu#23]

**Comment by McKay42** [comment]
Maybe only scale from 0.5 upwards, since playing with very low speed would become even more annoying to read due to extremely slow fadeout animations.

**Comment by AWWAMW** [comment]
I think everyone would still like to see and atleast try centipede 0.1 speed but otherwise, capping it to 0.5 might be indeed a good change.

**Comment by McKay42** [comment]
It's definitely going to be configurable with a convar
