### ISSUE TITLE
How to build on Linux?

### ISSUE THREAD

**Issue by jxu** [McKay42/McOsu#236]

**Comment by McKay42** [comment]
By reading the readme.

**Comment by jxu** [comment]
The README provides only download links and system requirements.

**Comment by McKay42** [comment]
> The README provides only download links and system requirements.
It also tells you that the game runs on McEngine.
The McOsu repository is only for the raw game code.

**Comment by jxu** [comment]
I suspected so but it would be nice to include that explicitly. 
I can even make a PR if necessary.

**Comment by iptq** [comment]
I agree that there should be more documentation about building; for example, what options were used for the release build?
