### ISSUE TITLE
BPM HUD gets stuck on highest BPM

### ISSUE THREAD

**Issue by SneakyLeif1020** [McKay42/McOsu#237]
It seems like it shows the correct BPM until the first note. After that, the HUD automatically changes to the highest BPM in the map.

**Comment by McKay42** [comment]
Is caused by having any speed multiplier != 1.0 and slow music loads and lead-in time, since the BPM is multiplied by the speed value set on the audio track (which only returns the correct value after it has been started/loaded, else it defaults to 1.0).

Fix will be in the next update.

**Comment by McKay42** [comment]
Fixed in 29.5
