### ISSUE TITLE
Custom Skin Path

### ISSUE THREAD

**Issue by IcePixelx** [McKay42/McOsu#241]
Since i'm one of the people that store there actual songs on another hard drive because of storage problems I always need to move my skins to a separate skins folder beside the songs folder in order to use them in McOsu.

I looked a bit around the code and saw that it uses a simple ConVar system to set the path of the folder and to retrieve it. So a checkbox in the config menu to use the system that i'm about to describe would make this easily possible.

Make a separate ConVar for the skinfolder.
If the checkbox is activated use that ConVar instead of the normal osu folder ConVar.

So I initially wanted to add it myself and see how it works out and make a pull request but I didn't mess around with Eclipse yet so I didn't get around doing it yet

**Comment by McKay42** [comment]
The current implementation works the other way round, by supporting the [BeatmapDirectory](https://osu.ppy.sh/help/wiki/osu%21_Program_Files/User_Configuration_File) parameter for existing osu installations (by parsing its config file).

**However**, in the current build, this would only work if an osu database also exists and is valid.
So, with the next update, I'll add support for it even if no osu database exists or is disabled in the options.
(And a tutorial for creating the necessary mock cfg file.)

**Comment by McKay42** [comment]
1. Your skins are here (i.e. each skin has its own subfolder in there): `C:/OsuStuff1/Skins/`
2. Your beatmaps are here (i.e. each beatmap has its own subfolder in there): `D:/OsuStuff2/`
3. Set your osu!folder to the **parent** folder of where your Skins folder is (e.g. `C:/OsuStuff1/`)
4. Notice how skins are now working, but beatmaps not yet of course.
5. Add a new text file to your osu!folder, with this specific filename/extension: `osu!.<SystemUsername>.cfg`
(replace `<SystemUsername>` with the username of the user account of your operating system)
e.g. `osu!.McKay.cfg`, with the following content: `BeatmapDirectory = D:/OsuStuff2/`
