### ISSUE TITLE
Add support for Optimus

### ISSUE THREAD

**Issue by Cherenkov11** [McKay42/McOsu#252]
I've noticed that when you play with "High performance nvidia" (gt 840m) it doesn't go to exclusive fullscreen mode, it just a type of borderless fullscreen, even with the compatibility option "Disable Fullscreen Optimization" enabled. But when execute McOsu with the integreted graphics card (Intel HD graphics 4400) it goes to exclusive fullscreen. Games like CSGO goes to exclusive fullscreen with the dedicated graphics card (Nvidia). All of this is due to that I feel input lag whenever I play with the nvidia graphics card.

BTW, I´m on windows 10 1909

**Comment by McKay42** [comment]
This is because CSGO uses DirectX instead of OpenGL.
DirectX only works on Windows, and therefore gets a bit of special treatment for some features.
Sorry, but there is not going to be a new renderer anytime soon.
