### ISSUE TITLE
Disable the little score screen for 

### ISSUE THREAD

**Issue by Bleikind** [McKay42/McOsu#260]
![grafik](https://user-images.githubusercontent.com/26650722/74371059-6fab6680-4dd8-11ea-8eb9-2f0f6709d089.png)

could it be possible to disable this thing?

**Comment by McKay42** [comment]
Why?

**Comment by Bleikind** [comment]
Its kinda annoying for me. Just an little tick to disable it?

**Comment by McKay42** [comment]
https://github.com/McKay42/McOsu/commit/6eed2454f0c8911006e7f0316f98c78d09941210
