### ISSUE TITLE
Some maps stuttering at start

### ISSUE THREAD

**Issue by NixXSkate** [McKay42/McOsu#261]
After the recent patch, certain maps seem to be stuttering at the start, both visually and audibly. Very noticeable with higher AR. May have to do with maps with hitcircles timed near the beginning of the first timing section. Examples: [https://osu.ppy.sh/beatmapsets/13833#osu/50907](https://osu.ppy.sh/beatmapsets/13833#osu/50907)
[https://osu.ppy.sh/beatmapsets/414667#osu/899565](https://osu.ppy.sh/beatmapsets/414667#osu/899565)

**Comment by McKay42** [comment]
Please try again with version 30.02, should be better.

Currently trying to find out how much interpolation time is needed when starting an mp3 before the [timing](https://www.un4seen.com/doc/#bass/BASS_ChannelGetPosition.html) stabilizes itself.

**Comment by McKay42** [comment]
Any updates on this? (Version 31.03 should further improve this)
