### ISSUE TITLE
 Suggestions for Improvement

### ISSUE THREAD

**Issue by Nesv17** [McKay42/McOsu#262]
Hello. I would like to ask you a couple of questions about the future of your game.
1)Will it be possible to view the replay in FPoSu
2)Will there be multiplayer and the ability to add other players friends
3)Will it be possible to edit the vertical FOV
4)Why was the map deceleration function removed and will it be returned

**Comment by McKay42** [comment]
> Hello. I would like to ask you a couple of questions about the future of your game.
> 1)Will it be possible to view the replay in FPoSu

No, sorry.

> 2)Will there be multiplayer and the ability to add other players friends

No, sorry.

> 3)Will it be possible to edit the vertical FOV

Already possible. Enable Options > FPoSu > "Vertical FOV".
Please READ through the options menu.

![Capture2](https://user-images.githubusercontent.com/16856443/74609162-ac80a180-50e7-11ea-86b2-503e6903c11f.PNG)


> 4)Why was the map deceleration function removed and will it be returned

What? Nothing was removed:

![Capture3](https://user-images.githubusercontent.com/16856443/74609231-742d9300-50e8-11ea-9238-2095d625aebb.PNG)

Use the "Speed/BPM Multiplier" slider to adjust the speed.

Not sure what you mean by "map deceleration function", but if you want a (admittedly useless for practicing) slowdown effect over the duration of an entire beatmap, you can customize the Timewarp mod via console commands:

Default (accelerate from 1x to 1.5x over time): `osu_mod_timewarp_multiplier 1.5`
Custom (decelerate from 1x to 0.75x over time): `osu_mod_timewarp_multiplier 0.75`

This is not what GitHub issues are for. If you have questions, ask them on the [forum](https://steamcommunity.com/app/607260/discussions/) or [Discord](https://discord.gg/3UQnt7X).
