### ISSUE TITLE
WMR Controller have no texture

### ISSUE THREAD

**Issue by Wuteva** [McKay42/McOsu#265]
IIRC about a year ago or so the controller were textured correctly.

See video : https://www.twitch.tv/videos/559451923
Tested on Samsung Odyssey

**Comment by McKay42** [comment]
That looks normal, play around with your Options > Virtual Reality > Play Area / Playfield > "RenderModel Brightness". This setting controls a color multiplier on how bright/dark the models are.

(Controller models and textures are provided by SteamVR, not the game.)

**Comment by Wuteva** [comment]
I see. I guess they changed it at some point. I'll try with the color multiplier, thanks!
