### ISSUE TITLE
You can fail with relax

### ISSUE THREAD

**Issue by crwn1337** [McKay42/McOsu#268]
title

**Comment by veronikazaglotova** [comment]
I think it wight be a feature

**Comment by barrack-obama** [comment]
You can change it in settings, search "HP Drain" and there should be an option between, None, osu!stable, osu!lazer, and McOsu

**Comment by McKay42** [comment]
I've been thinking about this, and it will stay the way it is.
Drain can be completely disabled as already mentioned, or alternatively you can disable "Kill Player upon Failing".
