### ISSUE TITLE
Fix score v1 drainLength

### ISSUE THREAD

**Issue by Magnus-Cosmos** [McKay42/McOsu#273]
https://github.com/McKay42/McOsu/blob/master/src/App/Osu/OsuScore.cpp#L178

The current drainLength equation is missing a floor function:

```c++
const unsigned long drainLength = std::floor(std::max(beatmap->getLengthPlayable() - std::min(breakTimeMS, beatmap->getLengthPlayable()), (unsigned long)1000) / 1000);
```

**Comment by McKay42** [comment]
This is an integer division, it is floored by definition (and floor only operates on floats, not unsigned longs).

Any specific reason why this came up?

**Comment by Magnus-Cosmos** [comment]
Sorry, forgot it was dealing with integers here. I was checking McOsu and osu! stable on some test maps to see if the scores matched, and I think McOsu was different on some of the maps, I'll need to double-check.

**Comment by McKay42** [comment]
Any updates on this? (I know that score v1 is not 100% accurate, but the deviations are small enough to not be worth investing even more time reverse engineering why)

**Comment by Magnus-Cosmos** [comment]
I agree, didn't have enough time to figure out what was causing the deviations, but they're pretty insignificant, plus I don't think anyone really cares much about score in McOsu, so I'll close the issue for now, maybe when I have some time, I'll try to figure out the cause of the deviations.
