### ISSUE TITLE
Map didn't render correctly

### ISSUE THREAD

**Issue by veronikazaglotova** [McKay42/McOsu#275]
https://www.youtube.com/watch?v=8tETapAqLJE
Here is a link, where I play a part of this https://osu.ppy.sh/beatmapsets/243#osu/1147 map
IIRC (last time when I played osu! was several weeks ago, anyway I have two passes on it so it should be humanly possible to pass it at least) 0:25 there should be a slider stream, but in McOsu it shows two slider streams in different places

**Comment by McKay42** [comment]
Nice catch, this is because of the BeatmapVersion being < 6.
Very old beatmaps use a special broken stacking algorithm, which I didn't know existed until now.

Will be fixed with the next update.

**Comment by McKay42** [comment]
Fixed in version 31.10
