### ISSUE TITLE
Add ranking-perfect support to ranking screen

### ISSUE THREAD

**Issue by veronikazaglotova** [McKay42/McOsu#276]
https://i.imgur.com/QmHnljp.jpg
This is an FC, https://osu.ppy.sh/beatmapsets/190390#osu/453358 here is a link to the beatmap, and when beatmap ended it doesn't show if it is an FC or not. Normally, in osu! it would have a "Perfect!" sign and a graph. This is extremely inconvenient, because in order to check if it as FC a player has to find the beatmap on osu.ppy.sh (for this song it is not a big problem, but if it has several different beatmaps with the same song it is very hard to find the right one) and check what is the maximum combo on that one difficulty.

**Comment by McKay42** [comment]
I somehow forgot this UI element existed, very weird.

This is easy to add, all McOsu scores store maxPossibleCombo, so I can retroactively add support for checking fc on every score.

Will be included in the next update.

**Comment by veronikazaglotova** [comment]
thx for renaming I'm really bad at english

**Comment by McKay42** [comment]
Included in version 30.10
