### ISSUE TITLE
McOsu won't check for new maps if osu!.db is enabled

### ISSUE THREAD

**Issue by veronikazaglotova** [McKay42/McOsu#277]
How to reproduce:

1. Open McOsu
2. Enable osu!.db if not enabled
3. Unarchive any osu!std map into Songs folder
4. Press F5 in the songs list
5. Try to search for just installed map

This only works if you unpack a map yourself, not if you drag&drop or open the file in osu!. I guess the problem is that osu!.db doesn't update and McOsu doesn't check the folder itself.

**Comment by McKay42** [comment]
osu! only writes the new database to disk when you either quit the game or set a new score.
Just restart or quit osu! for now, and then press F5 in McOsu songbrowser.

**Comment by veronikazaglotova** [comment]
But I don't have osu! installed, I only play McOsu
