### ISSUE TITLE
[Feature request] Add Wayland support?

### ISSUE THREAD

**Issue by veronikazaglotova** [McKay42/McOsu#281]
I tried running McOsu under GNOME on Wayland and noticed performance issues. McOsu was running under XWayland, I guess, this is probably why FPS was stuttering.
In the future, everyone will be running Wayland, because it solves several issues with rendering and security that X.Org has by design, so please, adopt McOsu for Wayland.

**Comment by McKay42** [comment]
Tracking at https://github.com/McKay42/McEngine/issues/92

> In the future, everyone will be running Wayland

We'll see about that.

If you want to play games, don't use Wayland at this point in time.
