### ISSUE TITLE
Gives me 2 errors at startup

### ISSUE THREAD

**Issue by KawaiiExeo** [McKay42/McOsu#289]
When i open McOsu! up it give me an error Couldn't RegisterRawInputDevices()! and when it is nearly done starting it gives me a sound error BASS_init() failed (23)! and when i press play on a map it says couldnt load the song file so i cannot play a single map which is pretty sad since i really wanna play McOsu is there any fix to this problem

**Comment by McKay42** [comment]
- This is the first time ever that RegisterRawInputDevices() has reportedly failed for someone (and the game has been out for 4+ years now).
- BASS_init() failing with error 23 means that you don't have a sound output device (or don't have a default output device, or the 
game is not allowed to access the device, or the device has failed in some fashion, or the driver has failed).

1. Does regular [osu!](https://osu.ppy.sh/home) work?
2. List your entire computer specs, including Windows version etc.
3. Is your Windows up to date?
4. What is your sound output device? (Windows > Settings > System > Sound > Output)
5. Read the [FAQ](https://steamcommunity.com/app/607260/discussions/0/1620599015885400990/) and run the debug exe, then copy paste the log from the cmd window here.

**Comment by KawaiiExeo** [comment]
My regular osu! does work
i5 processor 16gb ram 1050ti 4gb latest windows 10
its a pretty decent pc so i dont think this will be the problem
my sound output Speakers (2- High Definition Audio Device)
when i open debug.exe it thinks i wanna run it in vr so just skip that part
WARNING: Couldn't RegisterRawInputDevices(), GetLastError() = -2147023728
-= Engine Startup =-
McEngine v4 - Build Date: Jul 15 2020, 20:49:06
Engine: ScreenSize = (1280x720)
OpenGL: PixelFormat = 11
OpenGL: SetPixelFormat() = 1
OpenGL: OpenGL Version 4.6.0 NVIDIA 432.00
SoundEngine: BASS version = 0x02040f02
SoundEngine: Device 0 = "No sound", enabled = 1, default = 0
SoundEngine: initializeOutputDevice( -1, fallback = 0 ) ...
Sound Error: BASS_Init() failed (23)!
Trying to fall back to DirectSound ...
SoundEngine: initializeOutputDevice( -1, fallback = 1 ) ...
ERROR: [Sound Error] | BASS_Init() failed (23)!
Unable to read VR Path Registry from C:\Users\Badr\AppData\Local\openvr\openvrpaths.vrpath
ERROR: [OpenVR Error] | OpenVR runtime is not installed!
c:\buildslave\steam_rel_client_hotfix_win32\build\src\common\processpipe_any.cpp (246) : Assertion Failed: OpenFileMapping returned NULL (errno=2)
c:\buildslave\steam_rel_client_hotfix_win32\build\src\common\processpipe_any.cpp (246) : Assertion Failed: OpenFileMapping returned NULL (errno=2)
STEAM: SteamAPI_Init() failed!


and the rest is just it loading up the game

**Comment by McKay42** [comment]
Please switch to the [cutting-edge beta](https://imgur.com/a/KK2dcPF) and see if that fixes it.
(Steam Library > right click on the game > Properties > Betas > select "cutting-edge")

**Comment by KawaiiExeo** [comment]
McOsu cutting-edge still doesn't fix my sound problem i was looking through options and found the device output but it just says NULL and the other options for the sound is default only that just sets it back to NULL i can send you a video of me opening it if that will help

**Comment by McKay42** [comment]
> 
> 
> McOsu cutting-edge still doesn't fix my sound problem i was looking through options and found the device output but it just says NULL and the other options for the sound is default only that just sets it back to NULL i can send you a video of me opening it if that will help

Trying something else:

1. Please restart Steam to force the update I just pushed to the cutting-edge branch, and see if there is any change now
2. Copy paste the log like before

**Comment by KawaiiExeo** [comment]
I have already found a BASS_init() failed (23) fix by looking at what the errors said in the cmd however for the RegisterRawInputDevices() i cant find a fix but for me it doesnt really affect anything if someone else has the same BASS_init() failed (23) problem and nothing works tell them to delete the sound outputs they are not using atleast thats what worked for me

**Comment by McKay42** [comment]
> 
> 
> I have already found a BASS_init() failed (23) fix by looking at what the errors said in the cmd however for the RegisterRawInputDevices() i cant find a fix but for me it doesnt really affect anything if someone else has the same BASS_init() failed (23) problem and nothing works tell them to delete the sound outputs they are not using atleast thats what worked for me

The change I made should fix exactly that symptom, so you shouldn't have to delete these outputs.
Can you re-add them and check if everything works in the cuttind-edge beta?

**Comment by KawaiiExeo** [comment]
i readded them and still gives me both errors here is the log

WARNING: Couldn't RegisterRawInputDevices(), GetLastError() = 0
-= Engine Startup =-
McEngine v4 - Build Date: Aug 12 2020, 11:56:06
Engine: ScreenSize = (1280x720)
OpenGL: PixelFormat = 11
OpenGL: SetPixelFormat() = 1
OpenGL: OpenGL Version 4.6.0 NVIDIA 432.00
SoundEngine: BASS version = 0x02040f02
SoundEngine: Device 0 = "No sound", enabled = 1, default = 0
WARNING: SoundEngine::updateOutputDevices() found too many devices ...
SoundEngine: initializeOutputDevice( -1, fallback = 0 ) ...
Sound Error: BASS_Init() failed (23)!
Trying to fall back to DirectSound ...
SoundEngine: initializeOutputDevice( -1, fallback = 1 ) ...
ERROR: [Sound Error] | BASS_Init() failed (23)!
Unable to read VR Path Registry from C:\Users\Badr\AppData\Local\openvr\openvrpaths.vrpath
ERROR: [OpenVR Error] | OpenVR runtime is not installed!
c:\buildslave\steam_rel_client_hotfix_win32\build\src\common\processpipe_any.cpp (246) : Assertion Failed: OpenFileMapping returned NULL (errno=2)
c:\buildslave\steam_rel_client_hotfix_win32\build\src\common\processpipe_any.cpp (246) : Assertion Failed: OpenFileMapping returned NULL (errno=2)
STEAM: SteamAPI_Init() failed!

**Comment by McKay42** [comment]
Thanks for the logs, this is very weird.
Both clients use the exact same audio library, so I don't understand how there can be a difference in the device list.

Which output devices can you select in osu!, when at the same time McOsu can't find any output devices (you can run both clients at the same time)?

![Capture](https://user-images.githubusercontent.com/16856443/90053016-35b11380-dcda-11ea-84df-33f46303f1c8.PNG)
![Capture2](https://user-images.githubusercontent.com/16856443/90053171-66914880-dcda-11ea-95be-3562fffd3b61.PNG)

Please make a screenshot of which devices you can select in osu! in that state.

**Comment by KawaiiExeo** [comment]
Wow sorry for wasting ur time... my antivirus has messed up it was really bad and i tried to delete it but i couldnt so i canceled it half way deletion so it was like blocking every new installation and making them unstable but now i have fully deleted it and mcosu does work now sorry for the waste of time ... ;3

**Comment by McKay42** [comment]
> 
> 
> Wow sorry for wasting ur time... my antivirus has messed up it was really bad and i tried to delete it but i couldnt so i canceled it half way deletion so it was like blocking every new installation and making them unstable but now i have fully deleted it and mcosu does work now sorry for the waste of time ... ;3

That's ... also weird, I've never heard of antivirus software which specifically blocks audio output access? Maybe the BASS audio library initializes microphone access by default even though the game is not using it, and then the antivirus just blocks all access to all audio devices because of that.

Anyway, glad to hear it's working now.
