### ISSUE TITLE
Impossible to change keyboard key

### ISSUE THREAD

**Issue by bristow** [McKay42/McOsu#290]
Hi !

I tried to change the right click with 'e' letter but i didn't manage to do it, the focus is always on search.

Is there a tip ?

Thanks for your game !

**Comment by McKay42** [comment]
You have to click on the blue button to change a key binding, i.e. where the text "Left Click" is.

**Comment by McKay42** [comment]
![Capture](https://user-images.githubusercontent.com/16856443/91083465-a47f5c80-e64a-11ea-86c8-7ee84fd1b839.PNG)

**Comment by bristow** [comment]
Rohh, sorry ! 

Thanks !
