### ISSUE TITLE
Merge scores across accounts

### ISSUE THREAD

**Issue by cracento** [McKay42/McOsu#293]
Is there any way that I can merge my scores with both my Guest and main usernames? I didn't realize I was playing on Guest until about a week ago, and now I've racked up scores on both accounts. I looked at the scores.db file in HxD and I can't find a simple way to convert them over.

**Comment by McKay42** [comment]
Not at the moment. Something like this will be included in the next bigger update.

(While the scores.db is a relatively simple binary file, merging scores is non-trivial. So you'd have to write a tool for it, following the structure in [OsuDatabase](https://github.com/McKay42/McOsu/blob/master/src/App/Osu/OsuDatabase.cpp)::saveScores().)
