### ISSUE TITLE
Add option for audio pitch when using custom rate modifier.

### ISSUE THREAD

**Issue by Master-chan** [McKay42/McOsu#296]
Right now you can only pitch audio when using NC and it has constant pitch for x1.5 bpm.

**Comment by McKay42** [comment]
Use the `osu_pitch_override` ConVar to customize the pitch at any time, this overrides even NC.
e.g. reset (default value) = `osu_pitch_override -1`
e.g. 75% of normal pitch = `osu_pitch_override 0.75`
e.g. 150% of normal pitch = `osu_pitch_override 1.5`
Read the [FAQ](https://steamcommunity.com/app/607260/discussions/0/1620599015885400990/) on how to use the in-game console.

**Comment by Master-chan** [comment]
Thanks for the console var, but if you already have this functionality in client why can't you make an option that automatically changes it according to current speed modifier like in Quaver for example?

**Comment by McKay42** [comment]
Actually I think I misunderstood, what you want is the pitch to change together with the speed multiplier.

To do that, set `snd_speed_compensate_pitch 0`.
This will disable the pitch compensation for non-1.0x playback speeds.

The `osu_pitch_override` ConVar is only if you want to hardcode a specific pitch (regardless of speed).

**Comment by Master-chan** [comment]
Thank you, this is exactly what I wanted! Although I would still like to see it as checkbox in game options.

**Comment by McKay42** [comment]
> 
> 
> Thank you, this is exactly what I wanted! Although I would still like to see it as checkbox in game options.

You are only the third user to ask for it (I think), so I don't yet see a big enough reason for having it in the already huge options menu list. This is why console commands exist, so people can customize small details to their liking.
