### ISSUE TITLE
Feature Request: Random Mod Visible Seed + Insertable Seed

### ISSUE THREAD

**Issue by CCleanerShot** [McKay42/McOsu#298]
title. idk how its correctly done, but a visible seed of the randomizer and insertable numbers for that randomizer. been enjoying the mod but its hard to replay the same cool random version of a map.

**Comment by CCleanerShot** [comment]
bump

**Comment by Nanoo-web** [comment]
bump

**Comment by McKay42** [comment]
https://github.com/McKay42/McOsu/commit/412bc5eb93e3010c38756808d27aa052af99380b
