### ISSUE TITLE
Collections display the whole beatmapsets instead of just beatmaps

### ISSUE THREAD

**Issue by Thymue** [McKay42/McOsu#299]
Images for reference https://imgur.com/a/uTlnJm9

**Comment by Thymue** [comment]
#297 i'm blind

**Comment by vrecusko20** [comment]
haha~

**Comment by McKay42** [comment]
(This has already been fixed in the [rewrite](https://github.com/McKay42/McOsu/tree/rewrite) branch, the update will be out soon.)
