### ISSUE TITLE
Option "Draw HUD" doesn't toggle ScoreBar-bg and "Shift+Tab" also doesn't work on Linux

### ISSUE THREAD

**Issue by Cherenkov11** [McKay42/McOsu#301]
System Info:
OS: Linux
McOsu Version: 31.12

What happen?
Disabling the option "Draw HUD" does not toggle the option "Draw ScoreBar-bg" so it's still visible when it shouldn't be and needs to be disable manually.

Another issue, but more or less relatable:
Also on linux, the "Shift+Tab" shortcut does not work, mainly because of its harcoded nature, on linux there are two shift keys, Shift_L and Shift_R, so it doesn't get recognized by the shortcut. Maybe fixed by 6c49bd5

This also apply to "Scrubbing", the default bind is just "Shift" and it need to manually rebind to Shift_L to get recognized.

**Comment by McKay42** [comment]
1) "Draw HUD" not affecting scorebar-bg is fixed in f506d7daba34a911d326e79392a6e3a4a61b36e5
2) SHIFT is set to XK_Shift_L (X11 keysym) on linux by default, and works on Ubuntu. Pretty sure what you mean is fixed in 6c49bd5fcf0e033ae8aa54604a91e83a1e8e073d like you said.

**Comment by Cherenkov11** [comment]
1. Nice, thank you
2. Ok, checking the file Keyboard.cpp I can see that it looks for the KEYCODE KEY_SHIFT. On Arch Linux, according to evtest depending if you hit the left or the right shift it shows KEY_SHIFTLEFT and KEY_SHIFTRIGHT respectively. So, maybe that's the reason why it doesn't work for me. Perhaps if you add extra cases for the LEFT and RIGHT variant in the switch statement this could be resolve. Something similar happen to the control, alt and super key, they have the LEFT and RIGHT variant and not just the keycode alone. I don't' know if this apply to every linux distro. 

Note: I will try to compile McOsu by myself just to see if I can fix it

**Comment by McKay42** [comment]
Note that when I say "KEY_SHIFT", I am talking about McEngine key definitions, which are in [src/Engine/Platform/KeyboardKeys.h](https://github.com/McKay42/McEngine/blob/master/McEngine/src/Engine/Platform/KeyboardKeys.h).

There is nothing special for arch linux, as the XK_Shift_L macro is defined equally for all distros in [X11/keysymdef.h](https://www.cl.cam.ac.uk/~mgk25/ucs/keysymdef.h) under X11.

**Comment by Cherenkov11** [comment]
Well, in that case I'm lost
