### ISSUE TITLE
Visual Stuttering from AR override

### ISSUE THREAD

**Issue by Sowlokt** [McKay42/McOsu#304]
I've noticed some issues very recently (maybe new update) regarding performances while applying an AR override through the mod menu. I seem to be getting stuttering ranging from mild to unplayable.
There does not seem to be any difference in FPS between fluid states and visual stuterring states.
Do not seem to be map specific.
Does not seem to appear when the AR is changed through the use of HR / DT or Speed Multiplier
A reboot of McOsu seem to be reinitializing the states to something fluid.

Renderer settings :
Vsync off
High priority on (turning off increased my problems)
FPS Counter on
Unlimited FPS on
FPS Limiter 1000

Steps to reproduce : 
-Launch McOsu (up to date / steam)
-Select a map (I use https://osu.ppy.sh/beatmapsets/518003#osu/1100512 to make it easy to see the problem from the jumps -and low bpm)
-Through mods panel, (I use F1 key), manually override AR (I noticed the problem the most at 10.5 but it could depend on the player reading ability).

Following steps are unclear I messed around with them a little so these are the following things that made the problem appear for me :
-Play map
-Exit to menu
-Change the AR override again
-Play the map again or play another map
-Let the client run for some time or play more maps (it seemed to be time related or number of plays related).

That's about all I got for now.
Apart from that love the new update and game, thanks McKay!

**Comment by McKay42** [comment]
> 
> High priority on (turning off increased my problems)

This is a pretty big sign that your computer is at fault, i.e. some software is doing something in the background.

1) Are you on Windows/Linux/macOS? Which version?
2) Graphics driver version?
3) Third-party applications interfering with games (Discord Overlay, Steam Overlay, RivaTuner, Nvidia Control Panel, Nvidia GeForce Experience, AMD Crimson, etc.)?
4) Task manager CPU utilization and other running processes hogging the system?
5) Crappy antivirus software scanning in background?
6) Try disabling unlimited fps and playing with 1000 fps max?

**Comment by Sowlokt** [comment]
1.Windows 10. 20H2.
2. AMD Radeon 20.10.35.02-200821a-360470C-ATI for a RX 480 GPU. Here is the page of the driver version with some notes https://www.amd.com/en/support/kb/release-notes/rn-rad-win-20-11-1

3.Nope. Discord overlay disabled over all apps from settings, same for steam.
Maybe there was an unnoticed update of AMD Radeon Software that enabled some sort of recording for McOsu. I'll investigate further and keep you updated. But as far as I can remember I put all of those off for performance boost last time I set it up.

4. So during my previous attempt at fixing the issue I tried a few things on that end. Changing priority of McOsu to high and real time (from Normal) and it seemed to worthen the problem. Also tried putting McOsu on a single core (AMD ryzen 3600)
Performance apart from that specific problem didn't seem to be affected.
Notably Zoom was open at that time.
I'll retry reproducing issue with a lighter workload for the CPU and keep you updated.

5. Nothing.
6. Originally that were my settings and I had the same problem. So I tried to change to unlimited.
(Forgot to mention that, sorry)

**Comment by McKay42** [comment]
More questions:

7) What's your audio setup? Any weird razer/surround/usb/crap audio devices?
8) Any sound effect filters active? (e.g. Spatial Sound, Windows Sonic for Headphones, Audio Enhancements)
9) While in-game, hit CTRL + F11 to show the visual profiler. Start recording/photographing the profiler graph with a smartphone or something (do not record inside Windows) until while playing a beatmap you see whatever the stuttering is. Post the recordings here. If the graph is moderately stable then it's an audio(-time) problem.

**Comment by Sowlokt** [comment]
7. Sennheiser Momentum connected by jack to computer. Mic bird um1. These are quality devices.


8. I followed this guide from reddit to improve audio latency and input latency. https://www.reddit.com/r/osugame/comments/hqoakj/tutorial_removing_perceivable_latency_for_good/
So I have High Definition Audio Device windows audio drivers installed. Also used the REAL software mentionned in the previous reddit post to lower windows audio buffer latency.
Not to my knowledge. When I set the enhancement from that guide I made sure to disable and unistall all these.

9. 144hz. Yes fullscreen.

10. I'll try to get that.

More info on the problems : 
Later yesterday, after a few hours I tried reproducing the problem and couldn't. Computer was not restarted during that time, same session, no sleep mode either. Only difference was that zoom was now closed on my browser (and I had previous issues with the exe version of zoom but not with the browser version.)
I'll try to reproduce problem again later in the day and record it otherwise I'll close issue.
Thanks for your time until now.

**Comment by McKay42** [comment]
> Later yesterday, after a few hours I tried reproducing the problem and couldn't. Computer was not restarted during that time, same session, no sleep mode either. Only difference was that zoom was now closed on my browser (and I had previous issues with the exe version of zoom but not with the browser version.)
> I'll try to reproduce problem again later in the day and record it otherwise I'll close issue.

See, this is what I mean. There have been situations where having videos/streams playing in Firefox/Chrome caused massive stutters in running games. The problem comes from multiple programs trying to use the same hardware (in this case audio/video) combined with weird OS/driver behavior.

This is out of the control of the game. If you want a smooth gaming experience, then close all unnecessary programs and background services (including browsers sometimes, unfortunately).

**Comment by McKay42** [comment]
Closing this for now.

**Comment by Sowlokt** [comment]
Yep. Still not able to reproduce again. Must have been my computer.
Sorry for wasting your time and again thank you for this amazing McOsu!
