### ISSUE TITLE
Feature request: Buttons on the F1 menu to adjust CS, AR etc...

### ISSUE THREAD

**Issue by Oishun626** [McKay42/McOsu#308]
Since I am using a tablet to play, and I have a relatively high sensitivity. Sometimes it is hard for me to adjust my AR level from 10.2 to 10.3. And it is hard for me set the exact value I want in one drag.
So, I would like to add a button to add value to the stats. 
e.g. One click = add 0.1 value
It could really make a huge difference for me. Thank you!
Sorry for the bad English

**Comment by McKay42** [comment]
Hover your cursor over the slider you want to modify and use the LEFT/RIGHT arrow keys to adjust it.
Precise adjustments is what keyboards are for.
