### ISSUE TITLE
Hit error meter color mismatch from official client

### ISSUE THREAD

**Issue by PercyDan54** [McKay42/McOsu#314]
This is mcosu's hit error meter
![image](https://user-images.githubusercontent.com/50285552/120638271-80d32780-c4a2-11eb-9754-74ec13148814.png)

This is official osu's hit error meter
![image](https://user-images.githubusercontent.com/50285552/120638410-a6f8c780-c4a2-11eb-914d-ebef50370b9f.png)

There's a noticable color mismatch

Here's the color code from osu!fx:
``` CS
protected Color colour300 = new Color(50, 188, 231);

protected Color colour100 = new Color(87, 227, 19);

protected Color colour50 = new Color(218, 174, 70);
```

**Comment by McKay42** [comment]
Fixed in https://github.com/McKay42/McOsu/commit/b5803cd37dd3c27741b76744b5d141f425e9b33c
