### ISSUE TITLE
When holding a key somehow McOsu try to mke that holding pressing so fast and it will do that after you not hold a key anymore

### ISSUE THREAD

**Issue by dumb-stuff** [McKay42/McOsu#315]

**Comment by McKay42** [comment]
I don't understand what you mean, can you write step-by-step instructions on how to reproduce this?

**Comment by dumb-stuff** [comment]
1. install mcosu from steam
2.Enter random map
3.hold your key that bind to click circles
4. See your result at key overlay

**Comment by McKay42** [comment]
Which keys do you have bound for k1/k2?

**Comment by dumb-stuff** [comment]
> Which keys do you have bound for k1/k2?

A/S

**Comment by McKay42** [comment]
I can't reproduce this. Please record a video of it happening.

**Comment by dumb-stuff** [comment]
> I can't reproduce this. Please record a video of it happening.

Okay

**Comment by dumb-stuff** [comment]
@McKay42 
https://streamable.com/bckc90

**Comment by McKay42** [comment]
> https://streamable.com/bckc90

Your recording is broken, freezes after 2 seconds, try again.

**Comment by dumb-stuff** [comment]
@McKay42 here https://streamable.com/qan9f3 try this

**Comment by dumb-stuff** [comment]
My obs is overload so it lags
my bad

**Comment by McKay42** [comment]
> 
> 
> My obs is overload so it lags
> my bad

I can't see anything useful there because the recording is so extremely laggy.
How many fps do you get during regular playing?

**Comment by dumb-stuff** [comment]
> > My obs is overload so it lags
> > my bad
> 
> I can't see anything useful there because the recording is so extremely laggy.
> How many fps do you get during regular playing?

200 +

**Comment by McKay42** [comment]
Any update on this? If not then I'll close it next time I come here.
