### ISSUE TITLE
Extended VR Support - Quest

### ISSUE THREAD

**Issue by onkoe** [McKay42/McOsu#317]
Please consider expanding VR support to the Oculus Quest. It is currently the largest VR platform by far, and it runs on a somewhat customized version of Android with not much changed. Personally, I don't know how far your PCVR support goes, nor if it is actively maintained, but if it is, there is a great chance that most everything needed to port to Quest is already there. :-)

**Comment by McKay42** [comment]
I've explained this on Discord multiple times already, but I'm not interested in supporting any Facebook related projects besides not having enough free time to do so. Also I never intend to buy their headset (this stuff isn't free btw if you're just a hobby developer).

> runs on a somewhat customized version of Android

> there is a great chance that most everything needed to port to Quest is already there

That's not how this works. Creating an Android port of McOsu is not as simple as pressing the "Build Android Game" button, especially if it involves VR support, and even more so if it involves proprietary mobile device VR rendering.
