### ISSUE TITLE
[Feature request] Visual indicator of Experimental mods

### ISSUE THREAD

**Issue by apa420** [McKay42/McOsu#319]
I just started using the McOsu client because I wanted to try out the full alternating mod, but I couldn't find where it was so I thought it was removed.
Would be nice with a visual indicator of the experimental mods maybe similar to the vertical `osu!direct` in the standard client.
![](https://i.nuuls.com/KYm21.png)

**Comment by McKay42** [comment]
https://github.com/McKay42/McOsu/commit/a299ca47200a249db16ab7599c09d9746a9fe843

Will be in next update.
