### ISSUE TITLE
Experimental mod - Add x0.05 speed/BPM

### ISSUE THREAD

**Issue by Normaaannn** [McKay42/McOsu#323]
Or when half time mod is activated change the speed bar to x.x5, I know it sounds a bit dumb but its for increase or decrease less the speed for better skill progress

**Comment by McKay42** [comment]
Hold ALT while sliding any override slider to slide in 0.01 increments.

Alternatively, you can also enter exact speed override values via the in-game [console](https://steamcommunity.com/app/607260/discussions/0/1620599015885400990/):
`osu_speed_override 1.34`

**Comment by Normaaannn** [comment]
> 
> 
> Hold ALT while sliding any override slider to slide in 0.01 increments.
> 
> Alternatively, you can also enter exact speed override values via the in-game [console](https://steamcommunity.com/app/607260/discussions/0/1620599015885400990/): `osu_speed_override 1.34`

OMG thanks
