### ISSUE TITLE
[Help wanted] Export skin

### ISSUE THREAD

**Issue by RealMoondancer** [McKay42/McOsu#324]
I saw that you could export the current skin in the tooltip of the randomize Skin button but didn't find where.

**Comment by McKay42** [comment]
Read the [FAQ](https://steamcommunity.com/app/607260/discussions/0/1620599015885400990/) on how to use the in-game console.

As shown in the tooltip, the command for exporting the current skin is "osu_skin_export".

If you enter it without any value, then it will tell you to also give the exported skin a folder name, like "osu_skin_export RealMoondancer1234". This will create a new folder inside your /<osu!folder>/Skins/ subfolder called "RealMoondancer1234" and export the skin into it, so you could then restart osu! and select the skin "RealMoondancer1234".
