### ISSUE TITLE
Teleporting to certain sections of the map out of nowhere

### ISSUE THREAD

**Issue by StayBlueee** [McKay42/McOsu#325]
The title pretty much explains it all, I don't know why this issue happens. This has happened on numerous occasions.

It might have something to do with the full alternate mod (since that's the main mod I use)? I haven't tested that to be sure. This usually only happens on faster sections of the map or when a lot of notes appear at once.

I do notice that in the clip shown below that right before it happens it flashes a timestamp (potentially the time that it is teleporting to). Any potential fixes?

https://user-images.githubusercontent.com/23127866/142388429-83c11cc5-42bc-49a7-a4c4-db6696734dc3.mp4

Basic overview of my system
OS: Arch Linux
Kernel: Linux-tkg 5.12
Driver: Nvidia 460.73.01
Display Server: Xorg
Desktop Environment: KDE
Compositor: KWin

**Comment by McKay42** [comment]
You are hitting your SHIFT key (default scrubbing keybind, Options > Keyboard > In-Game) while playing.
Rebind it to a different key or be more aware of accidental key presses.
