### ISSUE TITLE
[Feature Request] Cursor Trail in FPOsu Mode.

### ISSUE THREAD

**Issue by TyroneBarkley** [McKay42/McOsu#336]
Hello, this is pretty straightforward. I'm pretty sure this isn't already possible as I have a cursor trail on my skin and it dissapears when I switch to FPOsu mode from normal osu mode. 

I don't know how hard this is to make, but I would really appreciate it if you would add this feature even as niche as it is because I've searched through the other requests to see if anyone had already asked this before and I don't believe anyone has. 

If I am wrong about it already being possible, please feel free to mark this feature request as closed. 

P.S. 
Thank you for making the best osu game in my opinion, until the developers of osu! come out with the new update, the game has been the same pretty much forever and there are certainly features that are lacking, not just the FPOsu part, simple additions like being able to customize your own CS size instead of getting screwed over by the makers of the beatmap is extremely helpful if you want to maintain consistency and probably takes more skill than "adjusting" everytime.

**Comment by McKay42** [comment]
https://github.com/McKay42/McOsu/commit/f3731799019a8782bb2df02f4b919df3df78b2d8

(Use the cutting-edge beta on Steam if you want to use it right now.)
![Capture](https://user-images.githubusercontent.com/16856443/166150392-e19de73c-3a74-4b17-a0cf-ab529d5c3633.PNG)

**Comment by TyroneBarkley** [comment]
You are the fucking best man.
