### ISSUE TITLE
Slider issues

### ISSUE THREAD

**Issue by ExCellRaD** [McKay42/McOsu#34]
Some small issues I found while playing:

- Repeating sliders don't always show their hit results at the correct sliderend
- The hidden fading sliders fade out too fast (the non-fast ones). They are completely hidden at 50% of the progress, this is even worse with repeat sliders.

**Comment by McKay42** [comment]
Repeat slider hitresult positions have been fixed, they were hardcoded to always use the "end" of the slider ignoring the repeats.

I'm not sure how osu sets the fadeout threshold, therefore I've added a command so people can modify the percentage value where the slider should be completely invisible as they wish in the meantime.
