### ISSUE TITLE
[Nitpick] Extrapolated Sliders

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [McKay42/McOsu#341]
osu! and osu!lazer has extrapolated slider that does extend in straight line but mcosu does not, (for perfect slider) it just spins around 3 points, and (for other types) just stops right there.
![osu_2022-10-26_23-38-11](https://user-images.githubusercontent.com/40109698/198056153-3f31fe43-f0f3-43f8-96ae-3e92717c131e.png)
![image](https://user-images.githubusercontent.com/40109698/198056206-63cad8d7-8cd0-47a4-924c-e69365e0e86b.png)
![image](https://user-images.githubusercontent.com/40109698/198056411-a94e0465-bfe4-4c6c-acb9-033fe5d2240e.png)

**Comment by McKay42** [comment]
Already tracked, see https://github.com/McKay42/McOsu/issues/185
