### ISSUE TITLE
Add the ability to drop bookmarks in a map

### ISSUE THREAD

**Issue by xolefray** [McKay42/McOsu#35]
By being able to drop bookmarks, one can practice precise sections of a map. For example, say there's a hard section coming up and i want to practice it; I drop a bookmark by pressing some arbitrary key so that when the section is over i can just press another arbitrary key to jump back to the bookmark to do the section all over again. In the current version I know that i can scroll through a song by CTRL+ALT+drag but it's not precise and it makes a painful sound.

**Comment by McKay42** [comment]
I wanted to make a fancy UI for this, but starting with two primitive hotkeys is better than nothing (Quick Save, Quick Load).
