### ISSUE TITLE
Load maps from osu LAZER

### ISSUE THREAD

**Issue by AymanLyesri** [McKay42/McOsu#357]
Is there a way to load maps from osu lazer folder?
am i missing something?

**Comment by McKay42** [comment]
Not possible atm because lazer uses a weird new db format (there is no normal "Songs" folder anymore). I've started working on a realm db loader but it's extremely annoying to integrate, meaning I gave up for now because time etc.

**Comment by exformation** [comment]
Would anyone be interested in working on this? Are there alternatives? I'm on Linux so I only use osu!lazer and it's getting more popular as a primary client.
