### ISSUE TITLE
Lag then pressing any key on the keyboard

### ISSUE THREAD

**Issue by NickTheHuy** [McKay42/McOsu#358]
Lately, there is a bug in which every time I press any key (to click the circles), there is a small lag, and when I play steam maps it becomes unplayable. Also, it doesnt affect the fps counter at all.
It's 100% sure not hardware issue since I'm using a good PC with RTX 3060TI

**Comment by NickTheHuy** [comment]
Also, its important to say, it happens only when playing a map, not in the menu

**Comment by McKay42** [comment]
Hit CTRL + F11 and check which color bar is the highest. This is very likely a software problem on your end, meaning the game can't do anything about it, so you have to fix it yourself.

**Comment by NickTheHuy** [comment]
![image](https://user-images.githubusercontent.com/84511935/235682087-6c177c25-1880-45a5-b46e-a414468df1d6.png)
this happens

**Comment by McKay42** [comment]
> ![image](https://user-images.githubusercontent.com/84511935/235682087-6c177c25-1880-45a5-b46e-a414468df1d6.png) this happens

Those big yellow lines mean that some other program running on your computer is freezing the game every time you press a key. It's your job now to figure out which program is interfering.

**Comment by NickTheHuy** [comment]
additionally, i restarted my pc and closed all processes but the windows ones, the bug still happens but only when i click when playing maps. it doesnt happen when its autoplay or when im clicking in song selection menu

**Comment by McKay42** [comment]
Close **ALL** other programs (Discord, Chrome, Skype, Teams, TeamSpeak, Firefox, Wallpaper Engine, Steam, MSI Afterburner, RivaTuner/RTSS, Corsair iCUE, Razer Chroma, GeForce Experience Overlay, etc.) and directly run McEngine.exe from /<Steam>/steamapps/common/McOsu/. The game can't do anything about random crap running on your system in the background, especially stuff like overlays which inject themselves into the game process and cause random bugs like that.

**Comment by NickTheHuy** [comment]
i did. as i said, i closed everything but microsoft windows processes used by the system itself that are nessecary for windows to function. still lag spikes and also 100% gpu usage every time i click

**Comment by McKay42** [comment]
> i did. as i said, i closed everything but microsoft windows processes used by the system itself that are nessecary for windows to function. still lag spikes and also 100% gpu usage every time i click

Let's try this:

- Delete all files in /\<Steam\>/steamapps/common/McOsu/cfg/
- Steam > Library > right click on McOsu > Properties > Local files > "Verify integrity of game files"
- Only configure your osu!folder and nothing else

See if that changes anything.

**Comment by NickTheHuy** [comment]
doesnt help

**Comment by NickTheHuy** [comment]
the lag is because 100% gpu usage

**Comment by McKay42** [comment]
Reinstall Windows or something, seems like your setup is broken. As this doesn't happen on any other machine besides yours, it is 100% something caused by a 3rd party application you have installed and/or running.
