### ISSUE TITLE
[Feature Request] Fully disable discord rich presence

### ISSUE THREAD

**Issue by DaGDNoob** [McKay42/McOsu#363]
Disabling rich presence in settings hides game information but rich presence is still active, it would be nice to completely disable it
![rich presence](https://github.com/McKay42/McOsu/assets/29365478/71db622f-a8cb-429f-abff-e4657ffde76c)

**Comment by McKay42** [comment]
As explained in the [FAQ](https://steamcommunity.com/app/607260/discussions/0/1620599015885400990/), add `-nodiscord` to the launch options.
