### ISSUE TITLE
beatmaps with modes other than zero don't show up (arch linux)

### ISSUE THREAD

**Issue by artistic-hacktivist** [McKay42/McOsu#364]
In the .osu file, there is a field called "mode", and unless this is set to 0, the game does not detect the map. Setting the mode on a broken map to 0 sometimes fixes it, but other times puts all the notes off screen.

**Comment by McKay42** [comment]
McOsu only supports osu!standard beatmaps. Any other gamemodes are not supported. See here: https://osu.ppy.sh/wiki/en/Client/File_formats/osu_(file_format)#general
