### ISSUE TITLE
left click become esc key

### ISSUE THREAD

**Issue by DDkhoa2k8** [McKay42/McOsu#372]
now every time I click any option in settings it will escape the setting
help me=))))

**Comment by McKay42** [comment]
Two options:

Open your `/<Steam>/steamapps/common/McOsu/cfg/osu.cfg` with Notepad++ or another text editor and search for the line starting with `osu_key_game_pause`. If bound to left click the full line will say `osu_key_game_pause 1`, replacing the `1` with a `0` will unbind the key.

Alternatively you could also simply delete your entire `/<Steam>/steamapps/common/McOsu/cfg/osu.cfg` file and then Steam > Library > right click on McOsu > Properties > Installed Files > "Verify integrity of game files" to redownload the default osu.cfg (this will reset all of your settings ofc).
