### ISSUE TITLE
Add ASIO or WASAPI sound output

### ISSUE THREAD

**Issue by mikezom** [McKay42/McOsu#39]
Sound output with low latency is extremely important for good gaming experience. The original latency of osu is unacceptable for those guys who have been used to playing low latency games such as LR2 or stepmania. So I wish that you can add low latency sound output type such as ASIO or WASAPI.

**Comment by McKay42** [comment]
After ~~9~~ 3 years in development, hopefully it will have been worth the wait.

Right click the game in your Steam library > Properties > BETAS > select "wasapi-test".

(This will stay a separate beta for the time being, because it has some sideeffects on timing/offsets)
