### ISSUE TITLE
Disable mouse clicks via F10 or options

### ISSUE THREAD

**Issue by ElementTimes682** [McKay42/McOsu#68]
You already know how this works, If you press F10, it will disable mouse clicks, this is highly useful for players that drag on tablets or accidentally misclick.

**Comment by CamelCaseMaster** [comment]
there is an option to disable mouse buttons + mouse wheel on the game's options menu ftm :3

**Comment by ElementTimes682** [comment]
Oh didn't see that. Would be still nice to have the F10 keybind there.

**Comment by McKay42** [comment]
Added keybind, will be in the next release
