### ISSUE TITLE
Osu! Working BUT McOsu! ISN'T

### ISSUE THREAD

**Issue by CamelCaseMaster** [McKay42/McOsu#69]
Hi! I play Osu! on both my laptop and my brother's

My Bruh's Laptop Specs :
Monitor 1366x768
Core i3-3120M 2.50 Ghz
Intel HD Graphics 4000 1.1 Ghz (Onboard OFC)
4Gb Ram

My Laptop Specs : 
Monitor 1366x768
Core2Duo T6670 2.2Ghz
Intel GMA 4500MHD (128 Vram)
8Gb Ram

so ram isn't an issue ofc Osu! is working fine on both laptops but my bruhs get >400 fps wheares mine get around 190-200 fps 

McOsu works on my brothers laptop but mine doesn't :'( 

PS : Directx and all visual c++ installed on both laptops 
       the gpu's drivers installed 
       both laptops got Windows 7 Ultimate 64Bit

last thing : each time i run Mcosu on my bruh's pc all 13gb of beatmaps get reloaded which slows down the computer ...

**Comment by McKay42** [comment]
Usually bug reports go into the discord > https://discord.gg/3UQnt7X

Your laptop's GPU only supports OpenGL 2.1, while McOsu currently needs OpenGL 3.0 for the RenderTargets necessary for drawing sliders. Spending time on making it work with old hardware is not going to happen in the near future of the Alpha phase, sorry :(

**Comment by CamelCaseMaster** [comment]
I knew it but I want to make sure No Problem ^^
