### ISSUE TITLE
New mod: Full Alternate

### ISSUE THREAD

**Issue by McKay42** [McKay42/McOsu#70]

**Comment by apa420** [comment]
Any reason for this mod being removed?

**Comment by McKay42** [comment]
> 
> 
> Any reason for this mod being removed?

What are you talking about? It's right there:

![Capture](https://user-images.githubusercontent.com/16856443/129479792-205e7879-5d60-4b6a-83cf-b19d1887d3d7.PNG)

**Comment by apa420** [comment]
I suppose I'm stupid, but I can't find this `Experimental Mods` tab anywhere.
I tried searching in settings after `mod` and `experimental` but couldn't find anything about it.
If it matters I'm using a 1440p screen.
![](https://i.nuuls.com/nCNQ3.png)
