### ISSUE TITLE
cursor freezes when using wacom 480

### ISSUE THREAD

**Issue by damnshes15** [McKay42/McOsu#89]
Works fine for my Huion 420 but my friend said it wasnt working with his 480

**Comment by McKay42** [comment]
I'm also using a CTL 480, tell your friend to use this: [http://viziblr.com/news/2011/8/13/fix-my-pen-makes-your-wacom-tablet-just-work-on-windows-7.html](http://viziblr.com/news/2011/8/13/fix-my-pen-makes-your-wacom-tablet-just-work-on-windows-7.html)

and also disable all the other useless crap like Windows Ink and Gestures

**Comment by damnshes15** [comment]
Oh wow thanks for the quick reply! I'll let him know about it
