### ISSUE TITLE
Autodetect AppData osu! installation

### ISSUE THREAD

**Issue by VelocityRa** [McKay42/McOsu#94]
*osu!* was installed at `C:\Users\<username>\AppData\Local\osu!` for me and I needed to enter that manually.

**Comment by McKay42** [comment]
This will need an engine change, a new Environment::getUsername() function or similar to return the current OS username (since there is no cross-platform way of getting the absolute path to the osu installation, this should satisfy the majority of users which are using Windows).

**Comment by McKay42** [comment]
Partially implemented in alpha 27, defaults to the user appdata osu dir (but doesn't check if osu is installed in C:/Program Files (x86)/)
