### ISSUE TITLE
Better randomness generation

### ISSUE THREAD

**Issue by VelocityRa** [McKay42/McOsu#96]
I'll do that myself.

**Comment by McKay42** [comment]
In the dev build, the random beatmap selection is now already using std::mt19937 seeded with time(0) upon startup, with a std::uniform_int_distribution for getting values. Is there a better solution (necessary?)?

**Comment by VelocityRa** [comment]
I didn't know this before creating the issue.
We _could_ use `chrono::high_resolution_clock` for the seed so that running at the same second doesn't produce the same results, but eh.
